// Generated by scripts/generate-roadmap-data.mjs from ROADMAP.md — do not edit by hand.
// Re-run `bun run generate:roadmap` after changing ROADMAP.md.
import raw from "./roadmap.json";

export type UnitStatus = "planned" | "in-progress" | "done";

export interface RoadmapUnit {
  number: string;
  slug: string;
  problem: string;
  tags: string[];
  status: UnitStatus;
}

export interface RoadmapTrack {
  name: string;
  units: RoadmapUnit[];
}

export const roadmap: { tracks: RoadmapTrack[] } = raw as {
  tracks: RoadmapTrack[];
};

export function getTrack(name: string): RoadmapTrack | undefined {
  return roadmap.tracks.find((t) => t.name === name);
}

export function getUnit(
  trackName: string,
  unitSlug: string,
): RoadmapUnit | undefined {
  return getTrack(trackName)?.units.find((u) => u.slug === unitSlug);
}
